const menuItems = [
  {
    name: "Noor Signature Kacchi Biryani",
    slug: "noor-signature-kacchi-biryani",
    category: "rice",
    description: "Premium basmati rice layered with marinated mutton, potato, saffron, and Noor Bistro's aromatic spice blend.",
    price: 1450,
    image: "https://images.unsplash.com/photo-1701579231344-7deed52b219f",
    isFeatured: true,
    isChefSpecial: true,
    isSpicy: false,
    available: true
  },
  {
    name: "Gulshan Morog Polao",
    slug: "gulshan-morog-polao",
    category: "rice",
    description: "Fragrant polao rice with tender chicken roast, caramelized onion, and subtle kewra aroma.",
    price: 1180,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    isFeatured: true,
    isChefSpecial: true,
    isSpicy: false,
    available: true
  },
  {
    name: "Old Dhaka Beef Tehari",
    slug: "old-dhaka-beef-tehari",
    category: "rice",
    description: "A rich Dhakaiya tehari with slow-cooked beef, mustard oil finish, and bold traditional spices.",
    price: 980,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
    isFeatured: true,
    isChefSpecial: false,
    isSpicy: true,
    available: true
  },
  {
    name: "Shorshe Ilish",
    slug: "shorshe-ilish",
    category: "seafood",
    description: "Fresh hilsa cooked in mustard gravy with green chili and Bengali home-style character.",
    price: 1650,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947",
    isFeatured: true,
    isChefSpecial: true,
    isSpicy: true,
    available: true
  },
  {
    name: "Prawn Malai Curry",
    slug: "prawn-malai-curry",
    category: "seafood",
    description: "Tiger prawns simmered in a velvety coconut milk sauce with gentle sweetness and spice.",
    price: 1380,
    image: "https://images.unsplash.com/photo-1563379091339-03246963d96c",
    isFeatured: true,
    isChefSpecial: true,
    isSpicy: false,
    available: true
  },
  {
    name: "Beef Kala Bhuna",
    slug: "beef-kala-bhuna",
    category: "mains",
    description: "Chattogram-inspired beef kala bhuna with deeply roasted spices and rich smoky flavor.",
    price: 920,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
    isFeatured: false,
    isChefSpecial: true,
    isSpicy: true,
    available: true
  },
  {
    name: "Chicken Roast Rezala",
    slug: "chicken-roast-rezala",
    category: "mains",
    description: "Tender chicken in a silky rezala-style gravy finished with nuts, cream, and aromatic spices.",
    price: 760,
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Mutton Bhuna",
    slug: "mutton-bhuna",
    category: "mains",
    description: "Slow-braised mutton cooked down in a thick onion-tomato masala with warming whole spices.",
    price: 1240,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947",
    isFeatured: false,
    isChefSpecial: true,
    isSpicy: true,
    available: true
  },
  {
    name: "Tandoori Pomfret",
    slug: "tandoori-pomfret",
    category: "seafood",
    description: "Whole pomfret marinated in yogurt, garlic, and tandoori spices, then flame grilled.",
    price: 1490,
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: true,
    available: true
  },
  {
    name: "Noor Mixed Grill",
    slug: "noor-mixed-grill",
    category: "mains",
    description: "A premium platter of kebab, grilled chicken, seekh, and charred vegetables for sharing.",
    price: 1890,
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783",
    isFeatured: true,
    isChefSpecial: true,
    isSpicy: true,
    available: true
  },
  {
    name: "Reshmi Kebab",
    slug: "reshmi-kebab",
    category: "starters",
    description: "Creamy and delicately spiced chicken kebabs served with mint yogurt.",
    price: 680,
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Mutton Seekh Kebab",
    slug: "mutton-seekh-kebab",
    category: "starters",
    description: "Juicy minced mutton skewers grilled with green chili, coriander, and charcoal smoke.",
    price: 840,
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783",
    isFeatured: false,
    isChefSpecial: true,
    isSpicy: true,
    available: true
  },
  {
    name: "Chicken Tikka",
    slug: "chicken-tikka",
    category: "starters",
    description: "Classic tikka pieces with a gentle spice level and signature Noor Bistro marinade.",
    price: 620,
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Fuchka Bites",
    slug: "fuchka-bites",
    category: "starters",
    description: "A refined plated take on Dhaka street-style fuchka with tangy tamarind water.",
    price: 390,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: true,
    available: true
  },
  {
    name: "Lentil & Smoked Chili Soup",
    slug: "lentil-smoked-chili-soup",
    category: "soups",
    description: "Velvety lentil soup infused with roasted garlic, smoked chili, and crisp onions.",
    price: 340,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Cream of Mushroom Soup",
    slug: "cream-of-mushroom-soup",
    category: "soups",
    description: "Smooth mushroom soup finished with cream, butter, and cracked pepper.",
    price: 360,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Butter Naan Basket",
    slug: "butter-naan-basket",
    category: "mains",
    description: "An assortment of butter naan and garlic naan baked fresh for the table.",
    price: 350,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Paneer Tikka Masala",
    slug: "paneer-tikka-masala",
    category: "mains",
    description: "Grilled paneer cubes in a luxurious tomato-cashew masala with gentle smokiness.",
    price: 720,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Thai Chili Chicken",
    slug: "thai-chili-chicken",
    category: "mains",
    description: "Crisp chicken tossed in a sweet-spicy chili glaze for guests who want an Asian fusion option.",
    price: 810,
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: true,
    available: true
  },
  {
    name: "Noor Special Fried Rice",
    slug: "noor-special-fried-rice",
    category: "rice",
    description: "Restaurant-style fried rice with egg, chicken, vegetables, and light wok aroma.",
    price: 640,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Borhani",
    slug: "borhani",
    category: "beverages",
    description: "Classic spiced yogurt drink served chilled and balanced for rich Bengali meals.",
    price: 220,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Aam Lassi",
    slug: "aam-lassi",
    category: "beverages",
    description: "Creamy mango yogurt drink made with ripe seasonal flavor and cardamom.",
    price: 260,
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Fresh Lime Soda",
    slug: "fresh-lime-soda",
    category: "beverages",
    description: "Refreshing lime soda with a choice of sweet or salted finish.",
    price: 180,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Saffron Firni",
    slug: "saffron-firni",
    category: "desserts",
    description: "Slow-cooked rice pudding scented with saffron, pistachio, and rose petals.",
    price: 320,
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    isFeatured: true,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  },
  {
    name: "Baked Mishti Doi",
    slug: "baked-mishti-doi",
    category: "desserts",
    description: "A rich baked yogurt dessert inspired by Bengal's classic sweet tradition.",
    price: 340,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777",
    isFeatured: false,
    isChefSpecial: false,
    isSpicy: false,
    available: true
  }
];

export default menuItems;
